/**
 * Generates a map of component ID → git creation date.
 * Runs at build/dev time so the dates are baked into the bundle.
 *
 * Usage: tsx scripts/generate-component-dates.ts
 */

import { execSync } from "node:child_process";
import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const COMPONENTS_DIR = join(process.cwd(), "src/components/thegridcn");
const OUTPUT_FILE = join(process.cwd(), "src/lib/component-dates.generated.ts");

function getGitCreationDate(filePath: string): string | null {
  try {
    // Get the date of the first commit that added this file
    const result = execSync(
      `git log --diff-filter=A --format=%aI -- "${filePath}"`,
      { encoding: "utf-8" }
    ).trim();
    // Take the last line (earliest commit) if multiple results
    const lines = result.split("\n").filter(Boolean);
    return lines.length > 0 ? lines[lines.length - 1].split("T")[0] : null;
  } catch {
    return null;
  }
}

function main() {
  const files = readdirSync(COMPONENTS_DIR).filter((f) => f.endsWith(".tsx"));
  const dates: Record<string, string> = {};

  for (const file of files) {
    const id = file.replace(/\.tsx$/, "");
    const filePath = join(COMPONENTS_DIR, file);
    const date = getGitCreationDate(filePath);
    if (date) {
      dates[id] = date;
    }
  }

  const content = `// Auto-generated by scripts/generate-component-dates.ts — do not edit manually
export const componentCreationDates: Record<string, string> = ${JSON.stringify(dates, null, 2)};
`;

  writeFileSync(OUTPUT_FILE, content, "utf-8");
  console.log(
    `Generated component dates for ${Object.keys(dates).length} components → src/lib/component-dates.generated.ts`
  );
}

main();
